# Generated by Django 4.0.2 on 2022-02-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pneu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pneu',
            name='medida',
            field=models.CharField(default='', max_length=255),
        ),
    ]
